const data=[
    {
        id:1,
        year:2024,
        category:"img",
        path:"images/gallery/pictures/1.jpg"
    },
    {
        id:2,
        year:2024,
        category:"img",
        path:"images/gallery/pictures/2.jpg"
    },
    {
        id:3,
        year:2024,
        category:"img",
        path:"images/gallery/pictures/3.jpg"
    },
    {
        id:4,
        year:2024,
        category:"img",
        path:"images/gallery/pictures/4.jpg"
    },
    {
        id:5,
        year:2024,
        category:"img",
        path:"images/gallery/pictures/5.jpg"
    },
    {
        id:6,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/6.jpg"
    },
    {
        id:7,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/7.jpg"
    },
    {
        id:8,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/8.jpg"
    },
    {
        id:9,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/9.jpg"
    },
    {
        id:10,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/10.jpg"
    },
    {
        id:11,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/11.jpg"
    },
    {
        id:12,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/12.jpg"
    },
    {
        id:13,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/13.jpg"
    },
    {
        id:14,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/14.jpg"
    },
    {
        id:15,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/15.jpg"
    },
    {
        id:16,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/16.jpg"
    },
    {
        id:17,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/17.jpg"
    },
    {
        id:18,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/18.jpg"
    },
    {
        id:19,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/19.jpg"
    },
    {
        id:20,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/20.jpg"
    },
    {
        id:21,
        year:2023,
        category:"img",
        path:"images/gallery/pictures/21.jpg"
    },
    {
        id:22,
        year:2022,
        category:"img",
        path:"images/gallery/pictures/22.jpg"
    },
    {
        id:23,
        year:2022,
        category:"img",
        path:"images/gallery/pictures/23.jpg"
    },
    {
        id:24,
        year:2022,
        category:"img",
        path:"images/gallery/pictures/24.jpg"
    },
    {
        id:25,
        year:2022,
        category:"img",
        path:"images/gallery/pictures/25.jpg"
    },
    {
        id:26,
        year:2022,
        category:"img",
        path:"images/gallery/pictures/26.jpg"
    },
    {
        id:27,
        year:2022,
        category:"img",
        path:"images/gallery/pictures/27.jpg"
    },
    {
        id:28,
        year:2022,
        category:"img",
        path:"images/gallery/pictures/28.jpg"
    },
    {
        id:29,
        year:2022,
        category:"img",
        path:"images/gallery/pictures/29.jpg"
    },



    {
        id:30,
        year:2022,
        category:"video",
        path:"https://www.youtube.com/embed/iBgUQNRQPO0"
    },
    {
        id:31,
        year:2022,
        category:"video",
        path:"https://www.youtube.com/embed/yFzBymyyQAs"
    },
    {
        id:32,
        year:2022,
        category:"video",
        path:"https://www.youtube.com/embed/0U3WN3f52x8"
    },
    {
        id:33,
        year:2024,
        category:"video",
        path:"https://www.youtube.com/embed/OMbNoo4mCcI"
    },
    {
        id:34,
        year:2024,
        category:"video",
        path:"https://www.youtube.com/embed/bC0hlK7WGcM"
    },
    {
        id:35,
        year:2024,
        category:"video",
        path:"https://www.youtube.com/embed/r6_3LzSsuBA"
    },
    {
        id:36,
        year:2024,
        category:"video",
        path:"https://www.youtube.com/embed/6niXo_L_q3Y"
    },
    {
        id:37,
        year:2024,
        category:"video",
        path:"https://www.youtube.com/embed/2ljlTABOaOc"
    },
    {
        id:38,
        year:2022,
        category:"video",
        path:"https://www.youtube.com/embed/RmmP_5Bck9Q"
    },
    {
        id:39,
        year:2023,
        category:"video",
        path:"https://www.youtube.com/embed/9jlP-48d-NA"
    },
    {
        id:40,
        year:2023,
        category:"video",
        path:"https://www.youtube.com/embed/Ehq_VweFBuU"
    },
    {
        id:41,
        year:2023,
        category:"video",
        path:"https://www.youtube.com/embed/Zfh4UVdjyyE"
    },
    {
        id:42,
        year:2023,
        category:"video",
        path:"https://www.youtube.com/embed/lLsPMZHfp6w"
    },
    {
        id:43,
        year:2022,
        category:"video",
        path:"https://www.youtube.com/embed/SxMpdf1GzxA"
    },
    {
        id:44,
        year:2023,
        category:"video",
        path:"https://www.youtube.com/embed/pT87hE70rfM"
    }


    
]